apiVersion: v2
name: cert-manager
description: A Helm chart for Kubernetes
type: application

# This is the chart version.
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: 1.0

dependencies:
- name: cert-manager
  version: 1.8.2
  repository: https://charts.jetstack.io