---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-python-k8s
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: templates/overlays/development
    repoURL: 'https://github.com/rajshivage/flask-python-k8s'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true