---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: templates/prometheus
    repoURL: https://github.com/rajshivage/kind-terraform-argocd.git
    targetRevision: HEAD
  syncPolicy:
    # automated:
    #   prune: false
    #   selfHeal: false
    syncOptions:
    - CreateNamespace=true